### ISSUE TITLE
How to run the laser only framework?

### ISSUE THREAD

**Issue by yanhaochiu** [spencer-project/spencer_people_tracking#61]
Hello,
This framework is pretty amazing,
I have a problem about the framework.
If I only want to use single laser scanner to detect and track people.
How do I run this framework?

Thanks for your help

**Comment by tlind** [comment]
You can take inspiration from this launch file:
https://github.com/spencer-project/spencer_people_tracking/blob/master/launch/spencer_people_tracking_launch/launch/tracking_single_rgbd_sensor.launch

But instead of front_rgbd_detectors.launch, include the following launch file with rear:=false:
https://github.com/spencer-project/spencer_people_tracking/blob/master/launch/spencer_people_tracking_launch/launch/detectors/laser_detectors.launch
